se agregaron variables,mixins e impotaciones
Sebastian0916/SemilleroDanna pull request #7
Opened 2024-06-25 21:23 UTC by danna222222

Se agregaron variables al tamaño y color del texto, mixins e importaciones

2024-06-25 22:20 UTC, David22zambrano commented on intro-figma-al-front/src/app/utilities/mixins.scss
> +@mixin tamaño($width, $height) {
Español o ingles?

2024-07-03 15:32 UTC, David22zambrano requested changes

2024-07-03 15:32 UTC, David22zambrano commented on proyecto-2/src/app/app.component.html
> +  <div class="main_container1 d-flex justify-content-between justify-content-center align-items-center pt-6 pb-10" >
Cambiar nombramiento de clases main_container1 no es un buen nombramiento

2024-07-03 15:32 UTC, David22zambrano commented on proyecto-2/src/app/app.component.html
> +  <div class="main_container1 d-flex justify-content-between justify-content-center align-items-center pt-6 pb-10" >
El figma dice padding-bottom de 10 ?

2024-07-03 15:32 UTC, David22zambrano commented on proyecto-2/src/app/app.component.html
> +    <button class="bg-primary  color-warn-50 "  mat-flat-button>
Asi no se pone color a un botton

2024-07-03 15:32 UTC, David22zambrano commented on proyecto-2/src/app/app.component.scss
> +.body1{
body1?

2024-07-03 15:32 UTC, David22zambrano commented on proyecto-2/src/app/app.component.ts
> +// export interface PeriodicElement {
TOdo ese codigo comentado ???

2024-07-03 15:32 UTC, David22zambrano commented on proyecto-2/src/app/app.component.ts
> +  // displayedColumns: string[] = ['Nombre', 'Habilitar', 'obligatorio','adjuntos','acciones'];
Mucho comentado que no debe ir

2024-07-03 15:32 UTC, David22zambrano commented on proyecto-2/src/app/componentes/table/table.component.scss
> +.slide_toggle{
porque le quemas tamaños ?

2024-07-03 15:32 UTC, David22zambrano commented on proyecto-2/src/app/componentes/table/table.component.scss
> +.column_nombre{
LA tabla no deebe tener modificaciones de estilos

2024-07-03 15:48 UTC, danna222222 commented on intro-figma-al-front/src/app/utilities/mixins.scss
> +@mixin tamaño($width, $height) {
Se ajusta el nombre del mixin

2024-07-03 16:35 UTC, danna222222 commented on proyecto-2/src/app/app.component.ts
> +// export interface PeriodicElement {
Se borro el codigo comentado

2024-07-03 16:36 UTC, danna222222 commented on proyecto-2/src/app/app.component.ts
> +  // displayedColumns: string[] = ['Nombre', 'Habilitar', 'obligatorio','adjuntos','acciones'];
Se borro el codigo comentado

2024-07-03 16:58 UTC, danna222222 commented on proyecto-2/src/app/componentes/table/table.component.scss
> +.column_nombre{
Se hizo la modificación de estilos

2024-07-03 17:00 UTC, danna222222 commented on proyecto-2/src/app/componentes/table/table.component.scss
> +.slide_toggle{
Se hizo la modificación de estilos

2024-07-03 17:01 UTC, danna222222 commented on proyecto-2/src/app/app.component.html
> +    <button class="bg-primary  color-warn-50 "  mat-flat-button>
Se hizo la modificación de estilos

2024-07-03 17:03 UTC, danna222222 commented on proyecto-2/src/app/app.component.html
> +  <div class="main_container1 d-flex justify-content-between justify-content-center align-items-center pt-6 pb-10" >
Se hizo la modificación del nombramiento

2024-07-03 17:03 UTC, danna222222 commented on proyecto-2/src/app/app.component.html
> +  <div class="main_container1 d-flex justify-content-between justify-content-center align-items-center pt-6 pb-10" >
Se hizo la modificación del padding

2024-07-03 17:33 UTC, danna222222 commented on proyecto-2/src/app/app.component.scss
> +.body1{
Se realizo la modificación del nombre de la clase

2024-07-04 14:04 UTC, David22zambrano requested changes

2024-07-04 14:04 UTC, David22zambrano commented on intro-figma-al-front/src/app/card/card/card.component.scss
> +    font-size: $small-font;
No puedes modificar las tipografias

2024-07-04 14:04 UTC, David22zambrano commented on intro-figma-al-front/src/app/utilities/variables.scss
> +//tipografias
NO se puede modificar tipografias

2024-07-04 14:08 UTC, David22zambrano approved these changes

2024-07-04 14:45 UTC, merged